config/routes.rb
Rails.application.routes.draw do

	devise_for :users, :controllers => {
		:registrations => 'users/registrations',
		:sessions => 'users/sessions',
		:omniauth_callbacks => 'users/omniauth_callbacks'
	}

	devise_scope :user do
		get "sign_in", :to => "users/sessions#new"
		get "sign_out", :to => "users/sessions#destroy"
	end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

	root 'homes#top'
	get '/about' => 'homes#about'
	get '/posts' => 'posts#new'
	get '/res' => 'posts#new'

	resources :users, only:[:show, :edit, :update]
	resources :res, only:[:show, :create, :edit, :update, :destroy] do
		resource :re_comments, only:[:create, :destroy]
	end
	resources :posts, only:[:new, :show, :create, :edit, :update, :destroy] do
		resource :likes, only:[:create, :destroy]
		resources :comments, only:[:create, :destroy]
		collection do
		  get :search
		end
	end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
	devise :database_authenticatable, :registerable,
	     :recoverable, :rememberable, :validatable,
	     :omniauthable, omniauth_providers:[:google_oauth2]


	has_many :posts, dependent: :destroy
	has_many :comments, dependent: :destroy
	has_many :likes, dependent: :destroy
	has_many :res, dependent: :destroy

	attachment :user_image

	validates :name, presence: true, length:{maximum: 20}
	validates :email, presence: true
	validates :profile, length:{maximum: 225}

	def soft_delete
		update_attribute(:deleted_at, Time.current)
	end

	def active_for_authentication?
		super && !deleted_at
	end

	def inactive_message
		!deleted_at ? super : :deleted_account
	end

	def self.from_omniauth(access_token)
		#p access_token
		data = access_token.info
		user = User.where(email: data['email']).first
		#p user
		unless user
			user = User.create(name: data['name'],
				email: data['email'],
				password: Devise.friendly_token[0,20]
			)
		end
		user
	end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
  def google_oauth2
    @user = User.from_omniauth(request.env['omniauth.auth'])
    if @user.persisted?
      flash[:notice] = I18n.t 'devise.omniauth_callbacks.success', kind: 'Google'
      sign_in_and_redirect @user, event: :authentication
    else
      session['devise.google_data'] = request.env['omniauth.auth'].except(:extra)
      redirect_to new_user_registration_url, alert: @user.errors.full_messages.join("\n")
    end
  end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
   def destroy
     resource.soft_delete
     Devise.sign_out_all_scopes ? sign_out : sign_out(resourse_name)
     set_flash_message :notice, :destroyed
     yield resource if block_given?
     respond_with_navigational(resource){redirect_to after_sign_out_path_for(resource_name)}
   end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, except:[:show]
  
  def show
  	@user = User.find(params[:id])
    @posts = @user.posts.page(params[:page]).reverse_order
  end

  def edit
  	@user = User.find(params[:id])
  end

  def update
  	@user = User.find(params[:id])
  	if @user.update(user_params)
        flash[:notice] = "ユーザー情報を更新しました"
        redirect_to user_path(@user.id)
    else
      flash.now[:alert] = "ユーザー情報の更新に失敗しました"
      render 'edit'
    end
  end

  private
  def user_params
  	params.require(:user).permit(:name, :user_image, :profile)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<div id = "row">
	<div class = "col-xs-offset-4 col-xs-4">
		<div id = "head">
			<h1>プロフィール設定</h1>
		</div>
		<%= render "layouts/error_message", model:@user %>
		
		<div class = "edit-user-form">
			<%= form_with model:@user, local: true do |f| %>
				<div class = "prev-image">
					<div class = "fild-img">
						<%= attachment_image_tag @user, :user_image, size:"300x300", fallback: "no_image.jpg", id:"post-img" %>
					</div>
					<%= f.attachment_field :user_image, id:"input-img" %>
				</div>
				<div class = "user-edit">
					<span class = "name-info">ニックネーム</span>
					<%= f.text_field :name, autofocus: true, placeholder:"ニックネーム" %>
				</div>
				<div class = "user-edit">
					<%= f.text_area :profile, size:"40x5", autofocus: true, placeholder:"自己紹介" %>
				</div>
				<div class = "update-user-btn">
					<%= f.submit "保存", class:"btn btn-primary" %>
				</div>
				|
				<div class = "hide-user-btn">
					<%= link_to "退会", user_registration_path, method: :delete, class:"btn btn-danger", data:{confirm:"退会処理を行います。よろしいですか？"} %>
				</div>
			<% end %>
		</div>
	</div>
</div>

app/views/users/show.html.erb
<div id = "row">
	<div id = "head">
		<h1><%= @user.name %>さんのページ</h1>
	</div>

	<div class= "col-xs-6 text-center">
		<div class="user-info">
			<%= attachment_image_tag @user, :user_image, size:"300x300", fallback: "no_image.jpg" %>
			<h4 class = "strong"><%= @user.name %></h4>
			<div class = "user-profile"><%= @user.profile %></div>
		</div>
		<% if @user == current_user %>
			<div class = "edit-user-btn">
				<%= link_to "変更する", edit_user_path, class:"btn" %>
			</div>
		<% end %>
	</div>

	<div class = "col-xs-6">
		<div class = "user-post">
			<table class = "table table-hover">
				<tr>
					<th>投稿日</th>
					<th>タイトル</th>
					<th></th>
					<th></th>
				</tr>

				<% if @posts.present? %>
					<% @posts.each do |post| %>
						<tr>
							<td><%= post.created_at.strftime('%Y/%m/%d') %></td>
							<td>
								<%= link_to post_path(post.id) do %>
									<%= post.title %>
								<% end %>
							</td>
							<td><%= render 'posts/badge', model:post%></td>
							<td>
								<% if post.user == current_user %>
									<div class = "post-delete-btn">
										<%= link_to "delete", post_path(post.id), method: :delete, class: "btn btn-danger", data: {confirm: '投稿を削除します。よろしいですか？'} %>
									</div>
								<% end %>
							</td>
						</tr>
					<% end %>
					<%= paginate @posts %>
				<% else %>
					<h3>まだ投稿はありません</h3>
				<% end %>
			</table>
		</div>
	</div>
</div>