config/routes.rb
Rails.application.routes.draw do

	devise_for :users, :controllers => {
		:registrations => 'users/registrations',
		:sessions => 'users/sessions',
		:omniauth_callbacks => 'users/omniauth_callbacks'
	}

	devise_scope :user do
		get "sign_in", :to => "users/sessions#new"
		get "sign_out", :to => "users/sessions#destroy"
	end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

	root 'homes#top'
	get '/about' => 'homes#about'
	get '/posts' => 'posts#new'
	get '/res' => 'posts#new'

	resources :users, only:[:show, :edit, :update]
	resources :res, only:[:show, :create, :edit, :update, :destroy] do
		resource :re_comments, only:[:create, :destroy]
	end
	resources :posts, only:[:new, :show, :create, :edit, :update, :destroy] do
		resource :likes, only:[:create, :destroy]
		resources :comments, only:[:create, :destroy]
		collection do
		  get :search
		end
	end
end

app/models/post.rb
class Post < ApplicationRecord

	belongs_to :user
	has_many :comments, dependent: :destroy
	has_many :likes, dependent: :destroy

	attachment :post_image

	validates :title, presence: true, length:{maximum: 30}
	validates :condition, presence: true, if: :is_status
	validates :explanation, presence: true, length:{maximum: 225}
	validates :selling_price, presence: true, if: :is_status
	validates :cycle, presence: true, unless: :is_status
	validates :is_burden, inclusion: [true, false]
	validates :is_status, inclusion: [true, false]

	enum condition: {新品や未使用: 0, 未使用に近い: 1, 目立った傷や汚れなし: 2, やや傷や汚れあり: 3, 傷や汚れあり: 4, 全体的に状態が悪い: 5}
	enum cycle: {リサイクル情報: 0, 買取店: 1, 寄付: 2, その他: 3}

	def liked_by?(user)
		likes.where(user_id: user.id).exists?
	end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, only:[:new, :edit]

  def new
    @post = Post.new
  end

  def create
    @post = current_user.posts.new(post_params)
    if @post.save
      flash[:notice] = "投稿が完了しました"
      redirect_to user_path(@post.user_id)
    else
      flash.now[:alert] = "投稿に失敗しました"
      render 'new'
    end
  end

  def show
    @post = Post.find(params[:id])
    @comments = @post.comments.page(params[:page]).reverse_order
    @comment = Comment.new
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      flash[:notice] = "投稿を更新しました"
        redirect_to post_path(@post.id)
    else
      flash.now[:alert] = "投稿の更新に失敗しました"
      render 'edit'
    end
  end

  def destroy
    post = Post.find(params[:id])
    post.destroy
    flash[:alert] = "投稿を削除しました"
    redirect_to user_path(current_user)
  end

  def search
  end

  private
  def post_params
    params.require(:post).permit(:title, :explanation, :selling_price, :post_image, :condition, :is_burden, :cycle, :is_status)
  end

end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_badge.html.erb
<% if model.is_status == true %>
	<span class = 'badge' style = "background-color:#0066FF"><p>フリマ</p></span>
<% else %>
	<span class = 'badge' style = "background-color:#00BB00;"><p>リサイクル</p></span>
<% end %>

app/views/posts/_like.html.erb
<% if user_signed_in? %>
	<% if model.liked_by?(current_user) %>
		<%= link_to post_likes_path(model), method: :delete do %>
			<dd><i class = "fas fa-heart" aria-hidden = "true" style = "color:red;"></i><%= model.likes.count %>いいね</dd>
		<% end %>
	<% else %>
		<%= link_to post_likes_path(model), method: :post do %>
			<dd><i class = "fas fa-heart" aria-hidden = "true"></i><%= model.likes.count %>いいね</dd>
		<% end %>
	<% end %>
<% else %>
	<dd><i class = "fas fa-heart" aria-hidden = "true" style = "color:red;"></i><%= model.likes.count %>いいねされています</dd>
<% end %>

app/views/posts/edit.html.erb
<div id = "row">
	<div id = "head">
		<h1>投稿編集</h1>
	</div>
	<%= form_with model:@post, local: true do |f| %>
		<div class = "col-xs-4 col-xs-offset-2 prev-img">
			<div c;ass = "find-img">
				<%= attachment_image_tag @post, :post_image, size:"300x300", fallback: "no_image.jpg", id:"post-img" %>
			</div>
			<%= f.attachment_field :post_image, id:"input-img" %>
		</div>

		<div class = "col-xs-6 text-center">
			<%= render "layouts/error_message", model:@post %>
			<div class = "update-post-form text-center">
				<div class = "update-post">
					<span class = "title-info">タイトル</span>
					<%= f.text_field :title %>
				</div>
				<div class = "update-post">
					<span class = "condition-info">商品状態</span>
					<%= f.select :condition, Post.conditions.keys %>
				</div>
				<div class = "update-post">
					<span class = "sales-info">売上高</span>
					<%= f.text_field :selling_price %>円
				</div>
				<div class = "update-post">
					<span class = "burden-info">送料負担</span>
					<% label :is_burden, "", value: true %>
					<%= f.radio_button :is_burden, true %>出品者負担
					<% label :is_burden, "", value: false %>
					<%= f.radio_button :is_burden, false %>購入者負担
				</div>
				<div class = "update-post">
					<span class = "body-info"></span>
					<%= f.text_area :explanation, size: "50x5" %>
				</div>
				<div class = "update-post-btn">
					<%= f.submit "更新", class:"btn" %>
				</div>
			</div>
		</div>
	<% end %>
</div>

app/views/posts/new.html.erb
<div id = "row">
	<div id = "head">
		<h1>投稿作成</h1>
	</div>

	<%= render 'layouts/error_message', model:@post %>
	<div class = "wrap">
		<ul id = "tab-menu" class = "clearfix">
			<li><a href = "#tab1" class = "active">フリマ経験談</a></li>
			<li><a href = "#tab2" class = "">リサイクル情報</a></li>
		</ul>

		<div id = "tab-contents" class = "clearfix">
			<div id = "tab1" class = "tab">
				<%= form_with model:@post, local: true do |f| %>
					<%= f.hidden_field :is_status, value: true %>
					
					<div class = "box1">
						<div class = "prev-img">
							<div class = "file-img">
								<%= attachment_image_tag @post, :post_image, size:"300x300", fallback: "no_image.jpg", id:"post-img" %>
							</div>
							<%= f.attachment_field :post_image, id:"input-img" %>
						</div>
					</div>

					<div class = "box2">
						<div class = "new-post-form text-center">
							<div class = "post-new">
								<lavel class = "title-info">タイトル</lavel>
								<%= f.text_field :title %>
							</div>
							<div class = "post-new">
								<lavel class = "condition-info">商品状態</lavel>
								<%= f.select :condition, Post.conditions.keys %>
							</div>
							<div class = "post-new">
								<lavel class = "sales-info">売上高</lavel>
								<%= f.text_field :selling_price %>円
							</div>
							<div class = "post-new">
								<lavel class = "burden-info">送料負担</lavel>
								<% label :is_burden, "", value: true %>
								<%= f.radio_button :is_burden, true %>出品者負担
								<% label :is_burden, "", value: false %>
								<%= f.radio_button :is_burden, false %>購入者負担
							</div>
							<div class = "post-new">
								<lavel class = "body-info"></lavel>
								<%= f.text_area :explanation, size: "50x5", placeholder: "詳細な説明" %>
							</div>
							<div class = "new-post-btn">
								<%= f.submit "投稿する", class:"btn" %>
							</div>
						</div>
					</div>
				<% end %>
			</div>

			<div id = "tab2" class = "tab">
				<%= form_with model:@post, local: true do |f| %>
					<%= f.hidden_field :is_status, value: false %>
					<div class = "box1">
						<div class = "prev-img">
							<div class = "file-img">
								<%= attachment_image_tag @post, :post_image, size:"300x300", fallback: "no_image.jpg", id:"re-img" %>
							</div>
							<%= f.attachment_field :post_image, id:"input-image" %>
						</div>
					</div>

					<div class = "box2">
						<div class = "new-post-form text-center">
							<div class = "post-new">
								<lavel class = "title-info">タイトル</lavel>
								<%= f.text_field :title %>
							</div>
							<div class = "post-new">
								<lavel class = "value-info">お得情報</lavel>
								<%= f.select :cycle, Post.cycles.keys %>
							</div>
							<div class = "post-new">
								<lavel class = "body-info"></lavel>
								<%= f.text_area :explanation, size: "50x5", placeholder: "詳細な説明" %>
							</div>
							<div class = "new-post-btn">
								<%= f.submit "投稿する", class:"btn" %>
							</div>
						</div>
					</div>
				<% end %>
			</div>
		</div>
	</div>
</div>

app/views/posts/search.html.erb
<div id = "row">
	<div class = "col-md-8 col-md-offset-2">
		<h3>検索結果一覧</h3>

		<table class = "table table-border">
			<div class = "no-border">
				<% if @results.present? %>
					<tr>
						<th>投稿日</th>
						<th width="40%">投稿者</th>
						<th>タイトル</th>
						<th>ジャンル</th>
					</tr>
					<% @results.each do |result| %>
						<tr>
							<td><%= result.created_at.strftime('%Y/%m/%d') %></td>
							<td>
								<%= attachment_image_tag result.user, :user_image, size:"50x50", class:"img-circle", fallback: "no_image.jpg" %>
								<%= link_to user_path(result.user) do %>
									<%= result.user.name %>
								<% end %>
							</td>
							<td>
								<%= attachment_image_tag result, :post_image, size:"50x50", fallback:"no_image.jpg" %>
								<%= link_to post_path(result.id) do %>
									<%= result.title %>
								<% end %>
							</td>
							<td><%= render 'posts/badge', model:result %></td>
						</tr>
					<% end %>
				<% else %>
				    <h3>該当する検索結果はありませんでした</h3>
				<% end %>
				<%= paginate @results %>
			</div>
		</table>
	</div>
</div>

app/views/posts/show.html.erb
<div class = "head-box row">
	<div id = "head">
		<h1><%= @post.title %></h1>
	</div>
	<div class = "col-xs-5 col-xs-offset-1">
		<div class = "post-show-img text-center">
			<%= attachment_image_tag @post, :post_image, size:"300x300", fallback: "no_image.jpg" %>
		</div>
	</div>

	<div class = "col-xs-5">
		<dl class = "single-post">
			<dt class = "post-show">
				<dd class = "item-show">商品状態：<%= @post.condition %></dd>
			</dt>
			<dt class = "post-show">
				<dd class = "sales-show">売上高：<%= @post.selling_price.to_s(:delimited) %>円</dd>
			</dt>
			<dt class = "post-show">
				<% if @post.is_burden == true %>
					<dd>送料負担：出品者負担</dd>
				<% else %>
					<dd>送料負担：購入者負担</dd>
				<% end %>
				</dd>
			</dt>
			<dt class = "post-show">
				<%= render 'posts/badge', model:@post %>
				<%= render 'posts/like', model: @post %>
			</dt>
			<dt class = "post-show">
				<dd class = "body-show">説明：<%= @post.explanation %></dd>
			</dt>
		</dl>
		<% if @post.user == current_user %>
			<div class = "edit-post-btn text-center">
				<%= link_to "編集する", edit_post_path(@post.id), class:"btn", method: :get %>
			</div>
		<% end %>
	</div>
</div>
<div class = "row ">
	<div class = "comment-area col-xs-6 col-xs-offset-3">
		<div class = "profile-area">
			<h3>投稿者</h3>
			<%= attachment_image_tag @post.user, :user_image, size:"60x60", fallback:"no_image.jpg", class:"img-circle profile-thumb center-block" %>
			<%= link_to user_path(@post.user) do %>
				<p><%= @post.user.name %></p>
			<% end %>
		</div>

		<div class = "comment-table">
			<h3>質問一覧</h3>
			<table class = "table table-border">
				<% if @comments.present? %>
					<tr>
						<th>質問者</th>
						<th>日時</th>
						<th>質問内容</th>
					</tr>
					<% @comments.each do |comment| %>
						<tr>
							<td width = "90">
								<%= comment.user.name %>さん
								<% if comment.user == current_user %>
									<div class = "comment-delete-btn">
										<%= link_to "delete", post_comment_path(comment.id), method: :delete, class: "btn btn-danger btn-xs", data: {confirm: '質問を削除します。よろしいですか？'}%>
									</div>
								<% end %>
							</td>
							<td><%= comment.created_at.strftime('%Y/%m/%d') %></td>
							<td><%= comment.comment %></td>
						</tr>
					<% end %>
				<% else %>
					<h4>この投稿に対する質問はありません</h4>
				<% end %>
				<%= paginate @comments %>
			</table>
		</div>

		<div class = "invite-box">
			<% if user_signed_in? %>
				<%= render "layouts/error_message", model:@comment %>
				<%= form_for [@post, @comment] do |f| %>
					<div class = "new-comment-form">
						<%= f.text_area :comment, size: "70x5", placeholder: "質問してみる", id:"comment-text" %>
					</div>
					<%= f.submit "質問する", id:"comment-submit", class: "btn btn-primary" %>
				<% end %>
			<% else %>
				<div class = "invite-new-user text-center">
					<h3>あなたも質問してみませんか？</h3>
					<%= link_to "新規登録", new_user_registration_path, class:"btn btn-primary" %>
					<p>既にアカウントを持っている方は<%= link_to "ログイン", new_user_session_path %></p>
				</div>
			<% end %>
		</div>
	</div>
</div>