config/routes.rb
Rails.application.routes.draw do

	devise_for :users, :controllers => {
		:registrations => 'users/registrations',
		:sessions => 'users/sessions',
		:omniauth_callbacks => 'users/omniauth_callbacks'
	}

	devise_scope :user do
		get "sign_in", :to => "users/sessions#new"
		get "sign_out", :to => "users/sessions#destroy"
	end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

	root 'homes#top'
	get '/about' => 'homes#about'
	get '/posts' => 'posts#new'
	get '/res' => 'posts#new'

	resources :users, only:[:show, :edit, :update]
	resources :res, only:[:show, :create, :edit, :update, :destroy] do
		resource :re_comments, only:[:create, :destroy]
	end
	resources :posts, only:[:new, :show, :create, :edit, :update, :destroy] do
		resource :likes, only:[:create, :destroy]
		resources :comments, only:[:create, :destroy]
		collection do
		  get :search
		end
	end
end

app/views/layouts/_error_message.html.erb
<% if model.errors.any? %>
	<div id = "error-explanation">
		<%= model.errors.count %>件のエラー
		<% model.errors.full_messages.each do |message| %>
			<P><%= message %></P>
		<% end %>
	</div>
<% end %>

app/views/layouts/_header.html.erb
<header>
	<nav class = "navbar-default">
		<div class = "container-fluid">
			<div class = "navbar-head">
				<button type = "button" class = "navbar-toggle collapsed" data-toggle = "collapse" data-target = "#zeni-navbar">
					<span class = "sr-only">toggle navigation</span>
					<span class = "icon-bar"></span>
					<span class = "icon-bar"></span>
					<span class = "icon-bar"></span>
				</button>

				<%= link_to '銭_get_back', root_path, class:"navbar-brand" %>
			</div>

			<div class = "collapse navbar-collapse" id = "zeni-navbar">
				<% if user_signed_in? %>
					<ul class = "nav navbar-nav">
						<li><%= link_to 'マイページ', user_path(current_user) %></li>
						<li><%= link_to '新規投稿作成', new_post_path %></li>
						<li><%= link_to 'ログアウト', sign_out_path %></li>
						<li><%= link_to 'サイトについて', about_path %></li>
					</ul>
					<p class = "navbar-text navbar-right">ようこそ<%= link_to current_user.name, user_path(current_user) %>さん</p>
				<% else %>
					<ul class = "nav navbar-nav">
						<li><%= link_to '新規登録', new_user_registration_path %></li>
						<li><%= link_to 'ログイン', sign_in_path %></li>
						<li><%= link_to 'サイトについて', about_path %></li>
					</ul>
					<p class = "navbar-text navbar-right">ようこそゲストさん</p>
				<% end %>
			</div>
		</div>
	</nav>
</header>

app/views/layouts/_notifications.html.erb
<div id = "flash">
	<% flash.each do |key, value| %>
		<%= content_tag(:div, value, class:"#{key}") %>
	<% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ZeniGetBack</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css'  %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body id = "wrapper">
      <%= render 'layouts/header' %>
      <%= render 'layouts/notifications' %>
      <div id = "container-fluid">
        <%= yield %>
      </div>
      <footer>
        <p>© All rights reserved by Hyouyou.</p>
      </footer>
  </body>
</html>